# docker-compose.yml

services:
  # Cliente GUI para Alice
  gui_alice:
    build: .
    container_name: alice_gui
    networks:
      - chat_net
    # --- SECCIÓN CRÍTICA PARA LA GUI ---
    environment:
      # Le dice a las aplicaciones GUI a qué display conectarse.
      - DISPLAY=$DISPLAY
      # Autenticación para X11 (el sistema de ventanas de Linux).
      - QT_X11_NO_MITSHM=1
    volumes:
      # Monta el socket del sistema de ventanas del anfitrión dentro del contenedor.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # ------------------------------------
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Comando para iniciar la aplicación GUI de Alice.
    command: python gui_main.py --user Alice --interface eth0

  # Cliente GUI para Bob
  gui_bob:
    build: .
    container_name: bob_gui
    networks:
      - chat_net
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Comando para iniciar la aplicación GUI de Bob.
    command: python gui_main.py --user Bob --interface eth0

networks:
  chat_net:
    driver: bridge
